# Generated by Django 4.1.7 on 2023-05-30 18:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_message_timestamp_alter_message_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancerequest',
            old_name='description',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='owner',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='received_maintenance_requests', to='accounts.webuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='accounts.webuser'),
        ),
    ]
