# Generated by Django 4.1.7 on 2023-06-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_maintenancerequest_owner_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='webuser',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
